default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development
test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>